<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>test-give-me-space-server</AssemblyName>
    <RootNamespace>TestGiveMeSpace.Server</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <StartupObject>TestGiveMeSpace.Server.Program</StartupObject>
    <RollForward>LatestMinor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestGiveMeSpace.Core\TestGiveMeSpace.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Mouse.png" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TestGiveMeSpace.Tests" />
  </ItemGroup>

</Project>
